### ISSUE TITLE
Manuscript preparation

### ISSUE THREAD

**Issue by liresearch** [liresearch/climate#1]
@alsamoua @luongcn Once you finished the first draft of the manuscript, please upload the draft to this repo. As suggested by @smiths, we will use it like Dropbox with commit messages for now.

**Comment by alsamoua** [comment]
We have uploaded a draft of our paper. Please let us know of any adjustments or changes we can make.
Thanks!

**Comment by alsamoua** [comment]
Hi @smiths,

We have uploaded a draft of our paper. Please let us know of any adjustments or changes we can make.

Thanks!

**Comment by smiths** [comment]
Great!  I will assign myself an issue to review the manuscript.  I have a paper deadline on Friday, so the review might have to wait until early next week.

**Comment by smiths** [comment]
Since the manuscript has been prepared, this issue can now be closed.
