### ISSUE TITLE
Formulas for R^2 and RMSE?

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#10]
I suppose the answer to this depends on the journal, but my first thought is that including the equations for R^2 and RMSE are not necessary.  These are very standard formulas.  However, maybe this information is important for an interdisciplinary audience?

**Comment by liresearch** [comment]
Yes, these are well-known statistics, but I have an impression that more often than not the formulas are provided when they are used for climate model evaluation. Maybe we can keep them unless the editor or reviewers suggest otherwise?

**Comment by smiths** [comment]
That makes sense to me.  They don't take up much space and having a paper with no equations would look "wrong."  😄
