### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#11]
I fear that Figure 2 will be too difficult to read.  Is it possible to show a representative plot of tas over time at one station?  If the point of the plots isn't to actually read the data, but get a sense of the amount of variation, then the figure should be fine.  The editor might ask for darker lines, but we don't need to stress about that initially.

**Comment by liresearch** [comment]
I think it may be better to keep all the sub-figures to show different patterns at the 12 stations, but I totally agree that we should make this figure easier to read. Maybe we can use three line/maker types to differentiate observation, multi-model simulation, and individual simulation, and then use different colors for each individual simulation? @luongcn

**Comment by smiths** [comment]
@liresearch, I agree with your suggestions to make the figure easier to read.  Another thing that helps with figures is to generate them as pdfs, not jpegs, gifs or pngs.  The vector format of the pdfs make the images crisper.  (I didn't check, so the original might already be a pdf, but if it isn't, the pdf format will help.)

**Comment by alsamoua** [comment]
[Annual Variation.pdf](https://github.com/liresearch/climate/files/1275301/Annual.Variation.pdf)
Is this figure easier to read or should I change the marker sizes and colours?

**Comment by luongcn** [comment]
Me and @alsamoua are trying to make it clear, however, the markers of observation and multi-model ensemble seem overlap other single models' markers. Does it matter? @liresearch @smiths

**Comment by liresearch** [comment]
The overlapping is fine. I'm afraid this is the best we can do if we want to add all data series on one plot.

**Comment by smiths** [comment]
I agree that there is no way to avoid the overlap at this scale.  I think the plot looks much nicer, and I cannot see a way to make it easier to read (other than to make it bigger, which isn't an option.)  I didn't notice another potential issue.  I'll create it as a separate issue.  I think we can close this one.
