### ISSUE TITLE
Figure 2 tas axes

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#13]
When looking at the new plot for Figure 2 that was produced to address issue #11, I noticed something else that we might want to fix.  Do we want the tas axes to have the same limits for each plot, or at least for each plot in the same row of plots?  If someone wants to compare the different plots, it is difficult, because the limits vary between -30 to 25, -10 to 25, -25 to 20 etc.  

If a comparison between plots is not really part of the point, please feel free to close this issue without any modification to the figure.

**Comment by liresearch** [comment]
My concern is if we use a wider range, the plots will be squeezed and it'll be even more difficult to see the differences between the observed and simulated values.  Considering that comparing model and observed fields is more import here, maybe we can keep it this way?

**Comment by smiths** [comment]
Agreed.  We should leave the figures as it is.
