### ISSUE TITLE
Detailed review of manuscript

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#14]
I believe that the first review of the manuscript (issue #4) has been completed.  I would still like to do a detailed review though, with feedback on the grammar and flow.  I've noticed some small problems that it would be better to sort out before sending it for review.

@luongcn, can you please push the latest version of the manuscript to the repo?

**Comment by alsamoua** [comment]
I have uploaded the latest version.

**Comment by smiths** [comment]
I completed a detailed review of the draft.  I dropped off a "marked up" copy of the paper with @liresearch.
