### ISSUE TITLE
Target for publication?

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#5]
Where are we aiming to publish the "Performance of a Multi-Model Ensemble for the Simulation for Temperature Variability Over Ontario, Canada"?  If there is a specific venue for the publication, I'd like to have a quick look at their manuscript requirements.

I'm going to assign this issue to @liresearch.  I will be doing the same for other issues that I'll be creating.  If someone else is a better choice to address the question/comment/issue, please go ahead and change the assignee.

**Comment by liresearch** [comment]
We are thinking about submitting it to _Climate Change_: 
https://link.springer.com/journal/10584
I have never published my work in this journal before, but have read many of their papers. I think it would be a good place to publish this work.
There are many other options (_Climate Dynamics, International Journal of Climatology_, etc.) - we can start from here and see how it goes. @smiths Please let me know what you think.

**Comment by smiths** [comment]
Yes, Climate Change looks like a good journal.  I think we are fine with the 12 page paper length.  I haven't checked the word count, but it definitely feels like a paper that could be delivered in 6000 words.  Once concern I do have is the journal's statement about the content of research articles:

"Original Research Articles submitted to Climatic Change should emphasize the interdisciplinary aspects of the research, especially in the context of illuminating new issues and insights regarding climatic change and attendant social, political, and environmental consequences."

There doesn't seem to be much of an emphasis on interdisciplinary studies in the current paper, or social, political and environmental consequences.  Maybe it would be worthwhile to send a copy of the abstract to an editor and verify that this type of submission fits their journal?  I had a string of desk rejects from editors lately because I was submitting my work to the wrong journals.  In my case I was submitting to journals outside of my usual area, so the problem was compounded, but, even in an area where you are familiar, a quick e-mail can help save time.  Desk rejects are very frustrating because all of the time spent to customize the paper to the specific needs of the journal is wasted.

In the end though, you are the expert and I am fine with whatever you recommend.

**Comment by liresearch** [comment]
I've seen several similar papers (papers that focus on climate modeling instead of interdisciplinary research) in this journal, but to on the safe side, I've sent an email to the editor to check the suitability of our paper. Thank you very much for the suggestion! I will keep you and @luongcn @alsamoua posted.

**Comment by smiths** [comment]
Thank you @liresearch.  I'm optimistic that you will get a positive response for the editor.  In which case we can then close this issue.

**Comment by liresearch** [comment]
I just received an ambiguous answer from the editor office:

"Please note that manuscripts presenting statistical trends or 
correlations in climate variables without novel data, methods, or 
insights or lacking plausible underlying physical models generally are 
not considered.
For further guidance, please browse the contents of our recent issues 
for a good idea of the kind of research that is published."

Since we are presenting new data and we've seen similar papers published in this journal, we might still have a shot. @smiths What do you think?

**Comment by smiths** [comment]
I am optimistic that the paper would be reviewed.  We, of course, cannot control whether it gets accepted, but what we really do not want is an editor's desk reject.  When you go to the effort of preparing a paper in the specific format required by a journal, having it immediately rejected is very disheartening.  (I've had it happen.)  😒  The editor certainly cannot say, at least without reviewer reports, that we don't match the aims of the journal.

We can certainly be optimistic that the paper will be reviewed and accepted.  However, even if rejected, we will get the reviewers comments that will allow us to improve the paper, either for resubmission to the same journal, or to a new journal.

@liresearch, I say we go with your instinct and submit the paper to Climate Change.  I'm going to close this issue.  If you feel otherwise, you can reopen it.  😄
