### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#6]
As a response to issue #4, I have reviewed about half of the manuscript.  I'm going to start posting issues now.  We'll see if this is an effective way to communicate.  If not, I can start putting comments in the Word file, but I'm not a big fan of Word and I'd like to avoid that, at least for a while.  😄 

Overall, I definitely like the paper.  It is well structured and tells a nice clean story.  I do have many little comments though, mainly with respect to the presentation.  If my comments are too low level for the current pass, please let me know.

On to the actual issue.  😄  I'm going to give some feedback on the abstract.  You can either make the suggested changes, or leave the abstract as it is.  Either way, you can close the issue once you've had a chance to review my thoughts.

The abstract seems too long to me, and I would like to see the conclusions quantified, if possible.  Specifically, I have the following comments/suggestions.  These items can be checked off as they are considered:

- [x] The first three sentences of the abstract seem to have too much "introductory" style information.  I think these three sentences could be combined into one sentence, followed by a modified version of sentence four.  Something like: "Multi-model ensembles for climate modeling, which have generally proven to have a superior performance compared to individual models, are assessed for Ontario, Canada.  The performance of seven GCM and RCM combinations were evaluated on twelve stations across Ontario as well as the whole domain."
- [x] The norms in the targeted journals might be different, but usually editors like to stay away from acronyms in abstracts.  Maybe GCM and RCM should be expanded as global and regional climate models, respectively?
- [x] on a similar note to the last bullet, I looked for the meaning of TS in the Climate Research Units TS.  I feel like the T stands for temperature, but I don't know what the S means.  Maybe this isn't even an acronym, but simply the name of the dataset?
- [x] Line 7 mentions "Three temperature variables" without saying what the variables are.  Maybe the variables could be added in brackets, like "Three temperature variables (average, maximum and minimum temperature) ... "
- [x] The "mostly" in the line 13, along with other parts of the sentence, sounds awkward to me.  I suggest rearranging the sentence to something like:  "For all three climate variables, at each station, and over the whole domain of Ontario, the multi ensemble based on the mean generally outperformed the ensemble based on median and each of the individual models."
- [x] I haven't finished reading the paper, but can the superior performance of the mean multi-model ensemble be quantified?  It is nice when the abstracts have quantified information.  If there is a statement in the paper about this, the specific details could go in the abstract.  Maybe there is an R^2 or a p value that could be mentioned?  If this quantification is not meaningful, you can ignore this comment.  😄 
- [x] Could any kind of quantification be added around the final sentence?  Maybe something out of the body of the paper, like "The multi-model mean ensemble predicts an increase in temperature of 2.89°C between the fifty-year historical period of 1951-2005 and the thirty-year future prediction period of 2040-2069."

**Comment by liresearch** [comment]
Thank you very much! These are all great suggestions! @luongcn @alsamoua please revise the abstract according and close this issue once you've finished the revision. (Please see my additional comments as below)

The norms in the targeted journals might be different, but usually editors like to stay away from acronyms in abstracts. Maybe GCM and RCM should be expanded as global and regional climate models, respectively?
==> Please remember to always use the full name when first used in the Abstract AND the text. 

on a similar note to the last bullet, I looked for the meaning of TS in the Climate Research Units TS. I feel like the T stands for temperature, but I don't know what the S means. Maybe this isn't even an acronym, but simply the name of the dataset?
==> In this case, I believe TS is simply the name of the dataset, but Aly and Kevin can double check.

I haven't finished reading the paper, but can the superior performance of the mean multi-model ensemble be quantified? It is nice when the abstracts have quantified information. If there is a statement in the paper about this, the specific details could go in the abstract. Maybe there is an R^2 or a p value that could be mentioned? If this quantification is not meaningful, you can ignore this comment. 
==> Yes, we have the R^2 of the 'mean' ensemble. We can add this in the abstract. 

Could any kind of quantification be added around the final sentence? Maybe something out of the body of the paper, like "The multi-model mean ensemble predicts an increase in temperature of 2.89°C between the fifty-year historical period of 1951-2005 and the thirty-year future prediction period of 2040-2069."
==> Great advice!
