### ISSUE TITLE
Text between headings?

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#7]
Somewhere along the line, I picked up the heuristic that there should be at least some text between my section headings.  The current draft of the paper violates this heuristic between "2. Methodology" and "2.1 Study Area and Data Collection", and similarly at the beginning of Section 3.  My usual approach is situations like this is to write a "roadmap" of the section as the blurb between the main section heading and the first of its subsections.  If there is a need to divide a section into subsections, an explanation of what is coming can help to orient the reader.

Your discipline norms might be different though, in which case, there is no need to add any text.

**Comment by liresearch** [comment]
You are absolutely right - this will make the logic much more clearer. @alsamoua @luongcn maybe we can add a "roadmap" for Section 3?
