### ISSUE TITLE
Low Information Content Phrases

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#8]
I noticed that the paper frequently uses "in order to," when a simple "to" would do the same job.  I suggest a search and replace to check each of these instances to see if the "in order" is actually necessary.

**Comment by liresearch** [comment]
@smiths Many thanks again for the valuable advice! @alsamoua please run through the manuscript and check this.

**Comment by smiths** [comment]
@alsamoua , when you complete your check, please close this issue.
