### ISSUE TITLE
Temperature variables

### ISSUE THREAD

**Issue by smiths** [liresearch/climate#9]
Are tas, tasmax and tasmin standard names for the temperature variables?  If they are, then there is no need to consider changing anything.  If not, there might be some variable names that would look a little nicer, like Tavg, Tmax and Tmin.  (The avg, max and min would be subscripts.)  I have a feeling though that tas etc is standard terminology.  They look like variable names in old FORTRAN programs.  😃

**Comment by liresearch** [comment]
tas, tasmax and tasmin are standard names in many climate models but not all models. We can use either '_tas_, _tasmax_ and _tasmin_', or '_Tmean_, _Tmin_, and _Tmax_ ', but not a mix of both. @luongcn Please run through the text, figures, and tables to make sure the variable names are consistent.

**Comment by smiths** [comment]
Thank you for the information @liresearch.  I prefer the second option, but given that "tas, tasmax and tasmin" is a standard choice,  you should stick with it.

What does the s stand for in tas?  I assume that the t is temperature, the a is average, but the s is not clear.  Station?

**Comment by alsamoua** [comment]
As indicated by the downloaded NA-CORDEX files, tas, tasmax and tasmin represent the average surface temperature, maximum surface temperature and minimum surface temperature respectively. I assume that the 's' stands for 'surface'

**Comment by luongcn** [comment]
I will go through all figures and text to make sure the acronyms we use are consistent @liresearch
